name: gift_grab
description: Game made using Flame where users grab presents to increase their scores.
publish_to: "none"
version: 1.6.0+16

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  build_runner: ^2.1.8
  cupertino_icons: ^1.0.2
  flame: ^1.4.0
  flame_audio: ^2.0.5
  flutter_dotenv: ^5.1.0
  flutter_login: ^5.0.0
  flutter_riverpod: ^2.3.6
  gap: ^3.0.1
  hive: ^2.2.3
  hive_generator: ^2.0.1
  intl: ^0.20.1
  json_serializable: ^6.7.0
  jwt_decoder: ^2.0.1
  lottie: ^3.1.2
  # nakama: ^1.1.0
  go_router: ^14.2.3
  path_provider: ^2.1.3
  toastification: ^2.0.0
  toggle_switch: ^2.0.1
  uuid:
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  freezed: ^2.4.6
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/lotties/
    - .env
