name: gift_grab
description: Game made using Flame where users grab presents to increase their scores.
publish_to: "none"
version: 1.6.0+16

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  build_runner: ^2.1.8
  cupertino_icons: ^1.0.2
  dio: ^5.7.0
  equatable: ^2.0.5
  flame: ^1.22.0
  flame_audio: ^2.0.5
  flame_bloc: ^1.12.4 
  flutter_bloc: ^8.1.3
  flutter_login: ^5.0.0 
  flutter_secure_storage: ^9.2.2
  gap: ^3.0.1
  go_router: ^14.2.3
  intl: ^0.20.1
  jwt_decoder: ^2.0.1
  lottie: ^3.1.2
  nakama: ^1.2.0
  path_provider: ^2.1.3
  toastification: ^2.0.0
  toggle_switch: ^2.0.1
  uuid:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
